version: "2.4"

services:
  api:
    build:
        context: ./
        dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
        context: frontend/
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
        - REACT_APP_BACKEND_URL=http://localhost:8000

